name:         The Final Countdown
nickname:     jQuery.countdown
baseurl:      http://hilios.github.io/jQuery.countdown
highlight:    true
markdown:     redcarpet
redcarpet:
  extensions:
    - with_toc_data
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
collections:
  examples:
    output: true
exclude:
  - node_modules/
